#"window.dynamic_title" = true

[colors.bright]
black = "0x565656"
blue = "0x49a4f8"
cyan = "0x99faf2"
green = "0xc0e17d"
magenta = "0xa47de9"
red = "0xec5357"
white = "0xffffff"
yellow = "0xf9da6a"

[colors.normal]
black = "0x2e2e2e"
blue = "0x47a0f3"
cyan = "0x64dbed"
green = "0xabe047"
magenta = "0x7b5cb0"
red = "0xeb4129"
white = "0xe5e9f0"
yellow = "0xf6c744"

[colors.primary]
background = "0x101421"
foreground = "0xfffbf6"

[cursor]
style = "underline"
unfocused_hollow = true

[env]
EDITOR = "nvim"
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 5000

[shell]
args = ["--login", "-c", "tmux attach || tmux -u"]
program = "/bin/zsh"

[window]
decorations = "None"
#gtk_theme_variant = "dark"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
