#!/bin/bash

# ensure unstow
stow -D --dotfiles zsh tmux
stow -D --dotfiles -t ~/.config dot-config/

# stow
stow --dotfiles zsh tmux
stow --dotfiles -t ~/.config dot-config/

read -p "Install packages? (y/n): " pkg_response
case $pkg_response in
    "yes"|"y")
	echo "installing..."
	if command -v apt &> /dev/null; then
	    echo "apt is available"
	    sudo apt install fzf ripgrep fd-find zsh tmux golang neovim nodejs
	fi

	if command -v dnf &> /dev/null; then
	    echo "dnf is available"
	    sudo dnf install fzf ripgrep fdfind zsh tmux golang neovim nodejs
	fi
	;;
    *)
	echo "skipping packages"
	;;
esac

read -p "Install asdf? (y/n): " asdf_response

case $pkg_response in
    "yes"|"y")
	if ! command -v asdf &> /dev/null; then
	    echo "asdf is missing, installing"
	    go install github.com/asdf-vm/asdf/cmd/asdf@latest
	fi
	asdf plugin add golang
	asdf install golang latest
	asdf set --home nodejs 22.14.0

	asdf plugin add nodejs
	asdf install nodejs 22.14.0
	asdf set --home nodejs 22.14.0

	asdf plugin add neovim
	asdf install neovim latest
	asdf set --home neovim latest
	;;
    *)
	echo "skipping asdf"
	;;
esac
