#!/bin/bash

mkdir -p .config/i3
mkdir -p .config/alacritty
mkdir -p .config/nvim
mkdir -p .config/kitty

echo "copying..."
cp $HOME/.config/kitty/kitty.conf .config/kitty/kitty.conf
cp $HOME/.config/alacritty/alacritty.yml .config/alacritty/alacritty.yml
cp $HOME/.config/i3/config .config/i3/config
cp $HOME/.zshrc .zshrc
cp $HOME/.tmux.conf .tmux.conf
cp -r $HOME/.config/nvim/ .config/nvim/
cp $HOME/.config/nvim/coc-settings.json .config/nvim/coc-settings.json
echo "done"
